WebApp/RouteSystem/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Route.Domain.Model;
using RouteSystem.Data;
using Serviceapplication.ServiceCity;

namespace RouteSystem.Controllers
{
    [Authorize]
    public class CitiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CitiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            return View(await ServiceCityApp.GetCity());
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await ServiceCityApp.SeachCity(id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,State,Id")] City city)
        {

          
            if (ModelState.IsValid)
            {
                ServiceCityApp.PostCity(city);
                return RedirectToAction(nameof(Index));

            }
            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await ServiceCityApp.SeachCity(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,State,CreatedAt,LastUpdateDate,User,Id")] City city)
        {



            if (id != city.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    city.Id = id;
                    var seachCity = await ServiceCityApp.SeachCity(id);
                    ServiceCityApp.UpdateCity(id, city);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var city = await ServiceCityApp.SeachCity(id);

            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var city = await ServiceCityApp.SeachCity(id);
            ServiceCityApp.DeleteCity(id);

            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(string id)
        {
            return _context.City.Any(e => e.Id == id);
        }
    }
}

WebApp/RouteSystem/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Route.Domain.Model;
using RouteSystem.Data;
using Serviceapplication.ServicePerson;

namespace RouteSystem.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await ServicePersonApp.GetPerson());
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await ServicePersonApp.SeachPerson(id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Status,Id")] Person person)
        {

         
            if (ModelState.IsValid)
            {
                ServicePersonApp.PostPerson(person);
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await ServicePersonApp.SeachPerson(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Status,Id")] Person person)
        {
         
            if (id != person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    person.Id = id;
                    var seachPerson = await ServicePersonApp.SeachPerson(id);
                    ServicePersonApp.UpdatePerson(id, person);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var person = await ServicePersonApp.SeachPerson(id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var person = await ServicePersonApp.SeachPerson(id);
            ServicePersonApp.DeletePerson(id);

            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(string id)
        {
            return _context.Person.Any(e => e.Id == id);
        }
    }
    }

WebApp/RouteSystem/Views/Shared/_Layout.cshtml
	@{
    string error = null;
    string success = null;

    if (TempData["error"] != null)
    {
        error = (string)TempData["error"];
    }
    if (TempData["success"] != null)
    {
        success = (string)TempData["success"];
    }
}

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RouteSystem</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/zephyr/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Route" asp-action="Create">Maximo Saúde e Bem Estar</a>
        

              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@if (SignInManager.IsSignedIn(User))
						{
							<li class="nav-item dropdown ">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Pessoas</a>
								<ul class="dropdown-menu navbar-dark">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="People" asp-action="Index">Lista de pessoas</a>
									</li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="People" asp-action="Create">Cadastrar</a>
									</li>
								</ul>
							</li>
							<li class="nav-item dropdown ">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Cidades</a>
								<ul class="dropdown-menu navbar-dark">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Cities" asp-action="Index">Lista de Cidades</a>
									</li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Cities" asp-action="Create">Cadastrar</a>
									</li>
								</ul>
							</li>

							<li class="nav-item dropdown ">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Equipes</a>
								<ul class="dropdown-menu navbar-dark">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="WorkTeams" asp-action="Index">Lista de Equipes</a>
									</li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="WorkTeams" asp-action="Create">Cadastrar</a>
									</li>
								</ul>
							</li>

							<li class="nav-item dropdown ">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Arquivos</a>
								<ul class="dropdown-menu navbar-dark">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Carregar arquivo</a>
									</li>								
								</ul>
							</li>

						}
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>  
         <div class="container">
        <main role="main" class="pb-3">
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Erro</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>@error</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalSuccess" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Sucesso</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>@success</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>
            @RenderBody()
        </main>
    </div>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
          		&copy; 2024, Todos os direitos reservados .
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    	<script>
			$(function () {
			  $('.dropdown-toggle').dropdown();
			});
		</script>
	  <script type="text/javascript">
        @if (error != null)
        {
            <text>
                $("#exampleModal").modal("show")
            </text>
        }
        @if (success != null)
        {
            <text>
                $("#modalSuccess").modal("show")
            </text>
        }
    </script>
</body>
</html>